cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

chifan/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('account.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('main.urls', namespace='main')),

    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(initial=1, min_value=1)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    class Meta:
        widgets = {
            'quantity': forms.TextInput(attrs={'class': 'form-control'})
        }

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import cTradeSubject
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(cTradeSubject, RecID=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(cTradeSubject, RecID=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    try:
        for item in cart:
            item['update_quantity_form'] = CartAddProductForm(
                initial={'quantity': item['quantity'],
                         'update': True})
    except:
        pass
    return render(request, 'cart/detail.html', {'cart': cart})

templates/cart/detail.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
<style>
        .product_amount{color:white; outline:none; background: transparent; display: inline-block; overflow: auto;text-align:center; border:none;}
    input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    /* display: none; <- Crashes Chrome on hover */
    -webkit-appearance: none;
    margin: 0; /* <-- Apparently some margin are still there even though it's hidden */
}

input[type=number] {
    -moz-appearance:textfield; /* Firefox */
}
</style>
    <div class="wrap_backet">
        <h1 class="backet_h1">Корзина</h1>
        <h2 class="backet_h2">Вы добавили в корзину</h2>
        <div class="backet_item_container">
            <div class="backet_item_container_block">
                {% for item in cart %}
                {% with product=item.product %}
                <div class="backet_item_container_block_item">
                    <div class="backet_item_container_block_item_img">
                        <img src="{{product.RecPict.url}}" alt="">
                    </div>
                    <div class="backet_item_container_block_item_desc">
                        <div class="backet_item_container_block_item_desc_info">
                            <h3>{{product.RecName}}</h3>
                            <h4>{{product.RecWeight}}</h4>
                        </div>
                        <div class="backet_item_container_block_item_desc_price">
                            <form action="{% url 'cart:cart_add' product.RecID %}" method="post">
                            <div class="backet_item_container_block_item_desc_price_amount">
                            <a href="#" class="product_minus">-</a>
                                {{ item.update_quantity_form.quantity|add_class:'product_amount' }}
                                {{ item.update_quantity_form.update }}
                            <a href="#" class="product_plus">+</a>
                            {% csrf_token %}

                            </div>
                            <div class="backet_item_container_block_item_desc_price_amount">
                                <input type="submit" value="Update"
                                       style="color:white; background: transparent; text-align:center; border:none;">
                            </div>
                        </form>
<!--                            <div class="backet_item_container_block_item_desc_price_amount" style="width:auto">-->
<!--                                <p class="product_amount">{{ item.quantity }}</p>-->
<!--                            </div>-->
                            <div class="backet_item_container_block_item_desc_price_value">
                                <h3>{{item.price}}</h3>
                                <h3>{{item.total_price}}</h3>
                                <p>(100 SWT)</p>
                            </div>
                        </div>
                    </div>
                    <div class="backet_item_container_block_item_delete"><a href="{% url 'cart:cart_remove' product.RecID%}">&#10006;</a></div>
                </div>
                {% endwith %}
                {% endfor %}
                <div class="backet_item_container_block_total">
                    <h3>Итого:</h3>
                    <h4>{{ cart.get_total_price }}</h4>
                    <p>(1000 SWT)</p>
                </div>
            </div>
            <div class="backet_item_container_qr">
                <img src="{% static 'img/qr.png' %}" alt="">
                <p>Отсканируйте код
                    для оплаты заказа</p>
            </div>
        </div>
        {% if cart %}
        <div class="backet_address">
            <h2>Оформить заказ</h2>
            <div class="backet_address_container">
                <div class="backet_address_container_text">
                    <h3>Россия, г. Кемерово, ул. Ноградская 5 – 404</h3>
                    <p>Напротив бара Суприм</p>
                </div>
                <div class="backet_address_container_ticket">
                    <img src="img/ticket.svg" alt="">
                </div>
            </div>
        </div>

        <div class="backet_bill">
            <h2>Выберите способ оплаты</h2>
            <div class="backet_bill_container">
                <input type="radio" id="SWT"
                name="contact" value="SWT" checked>
                <label for='SWT' class="backet_bill_block">
                    <p>SWT</p>
                </label>
                <input type="radio" id="TBCC"
                name="contact" value="TBCC">
                <label for='TBCC' class="backet_bill_block">
                    <p>TBCC</p>
                </label>
                <input type="radio" id="USDT"
                name="contact" value="USDT">
                <label for='USDT' class="backet_bill_block">
                    <p>USDT</p>
                </label>
            </div>
            <a href="{% url 'orders:order_create' %}">Оформить доставку</a>
        </div>

        <div class="backet_list">
            <div class="backet_list_info">
                <p>Доставка</p>
                <img src="{% static 'img/little_arrow.svg' %}" alt="">
            </div>
        </div>
        {% endif %}
        <div class="line"></div>

        <div class="backet_order">
            <h2>Ваша история заказов:</h2>
            <div class="backet_order_container">
                <div class="backet_order_block">
                    <div class="backet_order_block_text">
                        <h3>14:58 13 июля 2021</h3>
                        <h4>Заказ № 830048</h4>
                        <p>10¥  <span>(100 SWT)</span></p>
                    </div>
                    <div class="backet_order_block_img">
                        <img src="img/ticket.svg" alt="">
                    </div>
                </div>
                <div class="backet_order_block">
                    <div class="backet_order_block_text">
                        <h3>14:58 13 июля 2021</h3>
                        <h4>Заказ № 830048</h4>
                        <p>10¥  <span>(100 SWT)</span></p>
                    </div>
                    <div class="backet_order_block_img">
                        <img src="img/ticket.svg" alt="">
                    </div>
                </div>
                <div class="backet_order_block">
                    <div class="backet_order_block_text">
                        <h3>14:58 13 июля 2021</h3>
                        <h4>Заказ № 830048</h4>
                        <p>10¥  <span>(100 SWT)</span></p>
                    </div>
                    <div class="backet_order_block_img">
                        <img src="img/ticket.svg" alt="">
                    </div>
                </div>
            </div>
            <div class="backet_order_container">
                <div class="backet_order_block">
                    <div class="backet_order_block_text">
                        <h3>14:58 13 июля 2021</h3>
                        <h4>Заказ № 830048</h4>
                        <p>10¥  <span>(100 SWT)</span></p>
                    </div>
                    <div class="backet_order_block_img">
                        <img src="img/ticket.svg" alt="">
                    </div>
                </div>
                <div class="backet_order_block">
                    <div class="backet_order_block_text">
                        <h3>14:58 13 июля 2021</h3>
                        <h4>Заказ № 830048</h4>
                        <p>10¥  <span>(100 SWT)</span></p>
                    </div>
                    <div class="backet_order_block_img">
                        <img src="img/ticket.svg" alt="">
                    </div>
                </div>
                <div class="backet_order_button">
                    <a href="#">См. все</a>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
{% block scripts %}
    <script src = "https://code.jquery.com/jquery-latest.js"></script>
    <script src = "{% static 'js/backet.js' %}"></script>
{% endblock scripts %}