cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

chifan/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('account.urls')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('main.urls', namespace='main')),

    path('__debug__/', include('debug_toolbar.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('v1/', views.IndexView1.as_view(), name='v1'),
    path('v2/', views.IndexView2.as_view()),
    path('<int:pk>/', views.CatalogView.as_view()),
    path('search/', views.SearchView.as_view(), name='search'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SWT</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Exo+2:wght@400;500&family=Roboto:wght@400;500&display=swap" rel="stylesheet">


</head>
<body>
    <header class="header">
        <nav class="nav">
            <div class="wrap_menu">
                <div class="nav_container">
                    <div class="nav_logo">
                        <a href="{% url 'main:v1' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
                    </div>
                    <div class="nav_catalog">
                        <a href="" id="open_catalog" class="open_catalog">Каталог</a>
                        <div class="nav_catalog_container" id="nav_catalog_container">
                            <div class="nav_catalog_container_img">
                                <img src="" alt="" id="catalog_img">
                            </div>
                            <div class="nav_catalog_container_href">
                                {% for category in categories %}
                                    <a href="/{{category.RecID}}/" id="{{category.slug}}">{{category.RecName}}</a><br>
                                {% endfor %}
                            </div>
                            <div class="close_catalog" id="close_catalog">Закрыть</div>
                        </div>
                    </div>
                    <div class="nav_control">
                        <form action="{% url 'main:search' %}" method="get">
                            <input type="search" placeholder="Найдите то, что хотите" name="q">
                            <button type="submit"><img src="{% static 'img/search.svg' %}" alt=""></button>
                        </form>
                        <a href="{%url 'profile'%}" class="nav_man"><img src="{% static 'img/man_menu.svg' %}" alt=""></a>

                        <a href="{% url 'cart:cart_detail' %}" class="nav_backet"><img src="{% static 'img/backet.svg' %}" alt=""></a>
                        <div class="nav_language">
                            <img src="{% static 'img/russia.svg' %}" id='first_img' alt="">
                            <p id="name_first">Ru</p>
                            <a href="#" id="language_arrow"><img src="{% static 'img/language_arrow.svg' %}" alt=""></a>
                            <div class="nav_language_container" id='nav_language_container'>
                                <div class="nav_second_language" id="nav_second_language">
                                    <img id='second_img' src="{% static 'img/lang-en.svg' %}" alt="">
                                    <p id="name_second">En</p>
                                </div>
                                <div class="nav_third_language" id="nav_third_language">
                                    <img src="{% static 'img/lang-ch.svg' %}" id='third_img' alt="">
                                    <p id="name_third">Ch</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </nav>
        <div class="mobile_menu">
            <div class="mobile_menu_logo">
                <a href="/"><img src="{% static 'img/logo.png' %}" alt=""></a>
            </div>
            <div class="mobile_menu_nav">
                <span></span>
                <span class="middle_span"></span>
                <span></span>
            </div>
        </div>
        <div class="mobile_menu_block">
            <form action="">
                <input type="text" placeholder="Найдите то, что хотите">
                <button><img src="{% static 'img/search.svg' %}" alt=""></button>
            </form>
            <div class="mobile_menu_language">
                <div class="mobile_menu_language_item">
                    <img src="{% static 'img/russia.svg' %}" id='first_img' alt="">
                    <p id="name_first">Ru</p>
                </div>
                <div class="mobile_menu_language_item">
                    <img src="{% static 'img/lang-en.svg' %}" id='first_img' alt="">
                    <p id="name_first">En</p>
                </div>
                <div class="mobile_menu_language_item">
                    <img src="{% static 'img/lang-ch.svg' %}" id='first_img' alt="">
                    <p id="name_first">Ch</p>
                </div>
            </div>
            <div class="mobile_menu_href">
                <a href="catalog.html">Каталог</a>
                <a href="profile.html">Профиль</a>
                <a href="backet.html">Корзина</a>
            </div>
        </div>
        {% block main_image %}
        {% endblock main_image %}
    </header>
    {%block content%}
    {%endblock content%}
    <footer class="footer">
        <div class="wrap_main">
            <div class="footer_container">
                <div class="footer_info">
                    <img src="{% static 'img/logo2.png' %}" alt="">
                    <p>support-info@swt.ru</p>
                </div>
                <div class="footer_menu1">
                    <a href="#">Оплата</a><br>
                    <a href="#">Доставка</a><br>
                    <a href="#">Политика данных</a><br>
                </div>
                <div class="footer_menu2">
                    <a href="#">Техподдержка</a><br>
                    <a href="profile.html">Личный кабинет</a><br>
                    <a href="#">Акции и предложения</a><br>
                </div>
            </div>
            <div class="footer_item">
                <p>SWT, ©2022</p>
                <div class="footer_social">
                    <a href="" class="mail_icon_box">
                        <svg class="mail_icon">
                            <use xlink:href="{% static 'img/sprite.svg' %}#mail_icon"></use>
                        </svg>
                    </a>

                    <a href="" class="instagram_icon_box">
                        <svg class="instagram_icon">
                            <use xlink:href="{% static 'img/sprite.svg' %}#instagram_icon"></use>
                        </svg>
                    </a>

                    <a href="" class="telegram_icon_box">
                        <svg class="telegram_icon">
                            <use xlink:href="{% static 'img/sprite.svg' %}#telegram_icon"></use>
                        </svg>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    {% block scripts %}
    {% endblock scripts %}
    <script src = "https://code.jquery.com/jquery-latest.js"></script>
    <script src = "{% static 'js/slick.min.js' %}"></script>
    <script src = "{% static 'js/main.js' %}"></script>
</body>
</html>

templates/catalog.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<style>
    .product_amount{color:white; outline:none; background: transparent; overflow: auto;text-align:center; border:none;}
    input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    /* display: none; <- Crashes Chrome on hover */
    -webkit-appearance: none;
    margin: 0; /* <-- Apparently some margin are still there even though it's hidden */
}

input[type=number] {
    -moz-appearance:textfield; /* Firefox */
}
</style>
<div class="wrap_main">
    <h1 class="catalog_h1">{{category.RecName}}</h1>
    {% for subcategory in category.subcategories.all %}
    <section class="products">
        <h2>{{subcategory.RecName}}</h2>
        <div class="products_container">
            {% for product in subcategory.products.all %}
            <div class="products_block">
                <div class="products_block_button">
                    <a href="#"><img src="{% static 'img/like.svg' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/repost.svg' %}" alt=""></a>
                </div>
                <div class="products_block_img">
                    <img src="{{product.RecPict.url}}" alt="">
                </div>
                <div class="products_block_desc">
                    <p class="products_block_desc_name">{{product.RecName}}</p>
                    <p class="products_block_desc_weight">{{product.RecWeight}}</p>
                </div>
                <div class="products_block_info">
                    <form action="{% url 'cart:cart_add' product.RecID %}" method="post">
                            <div class="products_block_info_amount">
                            <a href="#" class="product_minus">-</a>
                            {% for hidden in cart_product_form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {% for field in cart_product_form.visible_fields %}
                                {{ field|add_class:'product_amount' }}
                            {% endfor %}
                            <a href="#" class="product_plus">+</a>
                            {% csrf_token %}

                            </div>
                            <div class="products_block_info_amount">
                                <input type="submit" value="Add"
                                       style="color:white; background: transparent; text-align:center; border:none;">
                            </div>
                        </form>
                    <div class="products_block_info_price">
                        <p class="products_block_info_price_bold">{{product.RecPrice}}</p>
                        <p class="products_block_info_price_medium">(100 SWT)</p>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </section>


    <section class="mobile_products">
        <h2>{{subcategory.RecName}}</h2>
        <div class="mobile_products_container">
            {% for product in subcategory.products.all %}
            <div class="mobile_products_block">
                <div class="mobile_products_block_button">
                    <a href="#"><img src="img/like.svg" alt=""></a>
                </div>
                <div class="mobile_products_block_img">
                    <img src="img/Haute Couture orange.png" alt="">
                </div>
                <div class="mobile_products_block_desc">
                    <p class="mobile_products_block_desc_name">{{product.RecName}}</p>
                    <p class="mobile_products_block_desc_weight">{{product.RecWeight}}</p>
                </div>
                <div class="mobile_products_block_info">
                    <div class="mobile_products_block_info_amount">
                        <a href="#" class="mobile_product_minus">-</a>
                        <p class="mobile_product_amount">1</p>
                        <a href="#" class="mobile_product_plus">+</a>
                    </div>
                    <div class="mobile_products_block_info_price">
                        <p class="mobile_products_block_info_price_bold">{{product.RecPrice}}</p>
                        <p class="mobile_products_block_info_price_medium">(100 SWT)</p>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </section>
    {%endfor%}
</div>
{% endblock content %}
{% block scripts %}
    <script src = "https://code.jquery.com/jquery-latest.js"></script>
    <script src = "js/slick.min.js"></script>
    <script src = "js/catalog.js"></script>

{% endblock scripts %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block main_image %}
<div class="main_img"></div>
{% endblock main_image %}

{% block content %}
<style>
    .product_amount{color:white; outline:none; background: transparent; overflow: auto;text-align:center; border:none;}
    input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
    /* display: none; <- Crashes Chrome on hover */
    -webkit-appearance: none;
    margin: 0; /* <-- Apparently some margin are still there even though it's hidden */
}

input[type=number] {
    -moz-appearance:textfield; /* Firefox */
}
</style>
<div class="wrap_main">
    <section class="about_us">
        <div class="about_us_container">
            <div class="about_us_block">
                <h2>Просто!</h2>
                <p>Достаточно подробное описание акции, но так</p>
            </div>
            <div class="about_us_block">
                <h2>Недорого!</h2>
                <p>Достаточно подробное описание акции, но так</p>
            </div>
            <div class="about_us_block">
                <h2>Бесплатная доставка!</h2>
                <p>Достаточно подробное описание акции, но так</p>
            </div>
        </div>
    </section>
    <section class="main_category">
        <h2>Категории товаров</h2>
        <div class="main_category_container">
            {% for category in categories %}
                <div class="main_category_block">
                    <a href="/{{category.RecID}}/">
                        <div class="main_category_block_desc">
                            {{category.RecName}}
                        </div>
                        <div class="main_category_block_img">
                            <img src="{{category.RecPict.url}}" alt="">
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </section>

    <section class="mobile_main_category">
        <h2>Категории товаров</h2>
        <div class="mobile_main_category_container">
            {% for category in categories %}
                <div class="mobile_main_category_block">
                    <a href="/{{category.RecID}}/">
                        <div class="mobile_main_category_block_desc">
                            {{category.RecName}}
                        </div>
                        <div class="mobile_main_category_block_img">
                            <img src="{{category.RecPict.url}}" alt="">
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </section>

    <section class="products">
        {% for category, products in data.items %}
        <h2>{{category}}</h2>
        <div class="products_container">
            {% for product in products %}
            <div class="products_block">
                <div class="products_block_button">
                    <a href="#"><img src="{% static 'img/like.svg' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/repost.svg' %}" alt=""></a>
                </div>
                <div class="products_block_img">
                    <img src="{{product.RecPict.url}}" alt="">
                </div>
                <div class="products_block_desc">
                    <p class="products_block_desc_name">{{product.RecName}}</p>
                    <p class="products_block_desc_weight">{{product.RecWeight}}</p>
                </div>
                <div class="products_block_info" style="display:block">

<!--                        <a href="#" class="product_minus">-</a>-->
<!--                        <p class="product_amount">1</p>-->
<!--                        <a href="#" class="product_plus">+</a>-->
                        <form action="{% url 'cart:cart_add' product.RecID %}" method="post">
                            <div class="products_block_info_amount">
                            <a href="#" class="product_minus">-</a>
                            {% for hidden in cart_product_form.hidden_fields %}
                                {{ hidden }}
                            {% endfor %}
                            {% for field in cart_product_form.visible_fields %}
                                {{ field|add_class:'product_amount' }}
                            {% endfor %}
                            <a href="#" class="product_plus">+</a>
                            {% csrf_token %}

                            </div>
                            <div class="products_block_info_amount">
                                <input type="submit" value="Add"
                                       style="color:white; background: transparent; text-align:center; border:none;">
                            </div>
                        </form>
                    <div class="products_block_info_price">
                        <p class="products_block_info_price_bold">{{product.RecPrice}}</p>
                        <p class="products_block_info_price_medium">(100 SWT)</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </section>

    <section class="mobile_products">

        {% for category in categories %}
        <h2>{{category.RecName}}</h2>
        <div class="mobile_products_container">
            {% for product in category.products.all %}
            <div class="mobile_products_block">
                <div class="mobile_products_block_button">
                    <a href="#"><img src="{% static 'img/like.svg' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/repost.svg' %}" alt=""></a>
                </div>
                <div class="mobile_products_block_img">
                    <img src="{{product.RecPict.url}}" alt="">
                </div>
                <div class="mobile_products_block_desc">
                    <p class="mobile_products_block_desc_name">{{product.RecName}}</p>
                    <p class="mobile_products_block_desc_weight">{{product.RecWeight}}</p>
                </div>
                <div class="mobile_products_block_info">
                    <div class="mobile_products_block_info_amount">
                        <a href="#" class="mobile_product_minus">-</a>
                        <p class="mobile_product_amount">1</p>
                        <a href="#" class="mobile_product_plus">+</a>
                    </div>
                    <div class="mobile_products_block_info_price">
                        <p class="mobile_products_block_info_price_bold">{{product.RecPrice}}</p>
                        <p class="mobile_products_block_info_price_medium">(100 SWT)</p>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div class="mobile_products_button">
                <a href="#">Eще</a>
            </div>
        </div>
        {% endfor %}
    </section>
</div>
{% endblock content %}

{% block scripts %}
    <script src = "https://code.jquery.com/jquery-latest.js"></script>
    <script src = "{% static 'js/slick.min.js' %}"></script>
    <script src = "{% static 'js/main.js' %}"></script>
{% endblock scripts %}

templates/index2.html
{% extends 'base.html' %}
{% load static %}

{% block main_image %}
<div class="main_img"></div>
{% endblock main_image %}

{% block content %}
<div class="wrap_main">
    <section class="about_us">
        <div class="about_us_container">
            <div class="about_us_block">
                <h2>Просто!</h2>
                <p>Достаточно подробное описание акции, но так</p>
            </div>
            <div class="about_us_block">
                <h2>Недорого!</h2>
                <p>Достаточно подробное описание акции, но так</p>
            </div>
            <div class="about_us_block">
                <h2>Бесплатная доставка!</h2>
                <p>Достаточно подробное описание акции, но так</p>
            </div>
        </div>
    </section>
    <section class="main_category">
        <h2>Категории товаров</h2>
        <div class="main_category_container">
            {% for category in categories %}
                <div class="main_category_block">
                    <a href="/{{category.RecID}}/">
                        <div class="main_category_block_desc">
                            {{category.RecName}}
                        </div>
                        <div class="main_category_block_img">
                            <img src="{{category.RecPict.url}}" alt="">
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </section>

    <section class="mobile_main_category">
        <h2>Категории товаров</h2>
        <div class="mobile_main_category_container">
            {% for category in categories %}
                <div class="mobile_main_category_block">
                    <a href="/{{category.RecID}}/">
                        <div class="mobile_main_category_block_desc">
                            {{category.RecName}}
                        </div>
                        <div class="mobile_main_category_block_img">
                            <img src="{{category.RecPict.url}}" alt="">
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </section>

    <section class="products">
        {% for category in categories %}
        <h2>{{category.RecName}}</h2>
        <div class="products_container">
            {% for product in products %}
            {% if product.RecGroupId.RecParentGroupId.RecID == category.RecID %}
            <div class="products_block">
                <div class="products_block_button">
                    <a href="#"><img src="{% static 'img/like.svg' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/repost.svg' %}" alt=""></a>
                </div>
                <div class="products_block_img">
                    <img src="{{product.RecPict.url}}" alt="">
                </div>
                <div class="products_block_desc">
                    <p class="products_block_desc_name">{{product.RecName}}</p>
                    <p class="products_block_desc_weight">{{product.RecWeight}}</p>
                </div>
                <div class="products_block_info">
                    <div class="products_block_info_amount">
                        <a href="#" class="product_minus">-</a>
                        <p class="product_amount">1</p>
                        <a href="#" class="product_plus">+</a>
                    </div>
                    <div class="products_block_info_price">
                        <p class="products_block_info_price_bold">{{product.RecPrice}}</p>
                        <p class="products_block_info_price_medium">(100 SWT)</p>
                    </div>
                </div>
            </div>
            {%endif%}
            {% endfor %}
        </div>
        {% endfor %}
    </section>

    <section class="mobile_products">

        {% for category in categories %}
        <h2>{{category.RecName}}</h2>
        <div class="mobile_products_container">
            {% for product in category.products.all %}
            <div class="mobile_products_block">
                <div class="mobile_products_block_button">
                    <a href="#"><img src="{% static 'img/like.svg' %}" alt=""></a>
                    <a href="#"><img src="{% static 'img/repost.svg' %}" alt=""></a>
                </div>
                <div class="mobile_products_block_img">
                    <img src="{{product.RecPict.url}}" alt="">
                </div>
                <div class="mobile_products_block_desc">
                    <p class="mobile_products_block_desc_name">{{product.RecName}}</p>
                    <p class="mobile_products_block_desc_weight">{{product.RecWeight}}</p>
                </div>
                <div class="mobile_products_block_info">
                    <div class="mobile_products_block_info_amount">
                        <a href="#" class="mobile_product_minus">-</a>
                        <p class="mobile_product_amount">1</p>
                        <a href="#" class="mobile_product_plus">+</a>
                    </div>
                    <div class="mobile_products_block_info_price">
                        <p class="mobile_products_block_info_price_bold">{{product.RecPrice}}</p>
                        <p class="mobile_products_block_info_price_medium">(100 SWT)</p>
                    </div>
                </div>
            </div>
            {% endfor %}

            <div class="mobile_products_button">
                <a href="#">Eще</a>
            </div>
        </div>
        {% endfor %}
    </section>
</div>
{% endblock content %}

{% block scripts %}
    <script src = "https://code.jquery.com/jquery-latest.js"></script>
    <script src = "{% static 'js/slick.min.js' %}"></script>
    <script src = "{% static 'js/main.js' %}"></script>
{% endblock scripts %}